import type { CharsetId } from "@/modules/tools/domain/charsets";
import { joinLines } from "@/modules/tools/domain/lines";
import { textToBytes } from "@/modules/tools/domain/text-codec";
import type { NewlineSeparator } from "@/modules/tools/types";
import type { UrlDecodeBytesResult, UrlEncodeProfile, UrlFailure } from "../types";
import { MAX_URL_INPUT_BYTES, URL_LINE_WIDTH } from "./constants";
import { keepsByteRaw } from "./profiles";

/**
 * RFC 3986 percent-encoding over raw bytes, so the same code path runs on the
 * server and in the browser and never depends on `encodeURIComponent`, which
 * speaks UTF-8 only and throws on a lone surrogate. Nothing here touches the
 * network or the DOM.
 */

const PERCENT = 0x25;

const PLUS = 0x2b;

const SPACE = 0x20;

/** Above this, a character cannot have come out of an encoder. */
const ASCII_MAX = 0x7f;

const HEX_DIGITS = { upper: "0123456789ABCDEF", lower: "0123456789abcdef" } as const;

const HIGH_SURROGATE_START = 0xd800;
const HIGH_SURROGATE_END = 0xdbff;
const LOW_SURROGATE_START = 0xdc00;
const LOW_SURROGATE_END = 0xdfff;

/**
 * A `%XX` triplet costs three code units and yields one byte, and no character
 * set this converter can write spends more than three bytes on a single code
 * unit — UTF-8's widest single-unit form. So the decoded output can never be
 * longer than three times the input, which lets it be written into one buffer.
 */
const MAX_BYTES_PER_CODE_UNIT = 3;

const encodeTables = new Map<string, readonly string[]>();

/* ---------------------------------------------------------------- encode --- */

/**
 * The escape a byte carries whenever it is encoded at all. Exported so the
 * reference table in the article is generated by the encoder it documents
 * rather than transcribed alongside it.
 */
export function percentEscape(byte: number, uppercaseHex = true): string {
    const digits = uppercaseHex ? HEX_DIGITS.upper : HEX_DIGITS.lower;

    return `%${digits[byte >>> 4]}${digits[byte & 0xf]}`;
}

/** The 256 fragments a profile can emit, built once and reused per byte. */
function encodeTable(profile: UrlEncodeProfile, uppercaseHex: boolean): readonly string[] {
    const key = `${profile}:${uppercaseHex}`;
    const cached = encodeTables.get(key);

    if (cached) {
        return cached;
    }

    const table = Array.from({ length: 256 }, (_, byte) => {
        // Form data is the one place a space is written as `+` rather than
        // escaped, which is also why it has to be decoded back deliberately.
        if (profile === "form" && byte === SPACE) {
            return "+";
        }

        return keepsByteRaw(profile, byte)
            ? String.fromCharCode(byte)
            : percentEscape(byte, uppercaseHex);
    });

    encodeTables.set(key, table);

    return table;
}

export function percentEncode(
    bytes: Uint8Array,
    profile: UrlEncodeProfile,
    uppercaseHex: boolean,
): string {
    const table = encodeTable(profile, uppercaseHex);
    let output = "";

    for (const byte of bytes) {
        output += table[byte];
    }

    return output;
}

/**
 * Breaks encoded output into fixed-width lines without ever splitting a `%XX`
 * triplet — a break between the `%` and its digits would leave two lines that
 * neither decode alone nor rejoin without stripping the separator first.
 */
export function wrapPercentEncoded(
    text: string,
    separator: NewlineSeparator,
    width: number = URL_LINE_WIDTH,
): string {
    if (width <= 0 || text.length <= width) {
        return text;
    }

    const lines: string[] = [];
    let start = 0;

    while (start < text.length) {
        const limit = Math.min(start + width, text.length);
        let end = limit;

        if (end < text.length) {
            if (text[end - 1] === "%") {
                end -= 1;
            } else if (text[end - 2] === "%") {
                end -= 2;
            }
        }

        // A width narrower than a triplet could otherwise back off to nothing
        // and never advance.
        if (end <= start) {
            end = limit;
        }

        lines.push(text.slice(start, end));
        start = end;
    }

    return joinLines(lines, separator);
}

/* ---------------------------------------------------------------- decode --- */

function hexValue(code: number): number {
    if (code >= 0x30 && code <= 0x39) {
        return code - 0x30;
    }

    if (code >= 0x41 && code <= 0x46) {
        return code - 0x41 + 10;
    }

    if (code >= 0x61 && code <= 0x66) {
        return code - 0x61 + 10;
    }

    return -1;
}

function isHighSurrogate(code: number): boolean {
    return code >= HIGH_SURROGATE_START && code <= HIGH_SURROGATE_END;
}

function isLowSurrogate(code: number): boolean {
    return code >= LOW_SURROGATE_START && code <= LOW_SURROGATE_END;
}

/**
 * Turns percent-encoded text back into bytes.
 *
 * A percent-encoded string is an ASCII byte stream (RFC 3986 §2), so an
 * unescaped ASCII character *is* its byte and is written straight through. Only
 * that reading survives a destination set that is not ASCII-compatible: in
 * UTF-16LE the encoder emits `A%00` for "A", and passing the literal `A` back
 * through the character set would produce two bytes where the stream holds one.
 *
 * Characters above ASCII cannot have come from an encoder at all, so they are
 * taken as typed text and written through the destination set. That is what
 * lets a half-encoded string such as `café%20au%20lait` decode as a whole
 * rather than being rejected.
 *
 * Positions in a failure count characters, not UTF-16 code units, so an emoji
 * earlier in the input does not throw the number off.
 */
export function percentDecode(
    input: string,
    charset: CharsetId,
    plusAsSpace: boolean,
): UrlDecodeBytesResult {
    const bytes = new Uint8Array(input.length * MAX_BYTES_PER_CODE_UNIT);
    let written = 0;
    let literal = "";
    let literalStart = 1;
    let index = 0;
    let position = 0;

    /** Writes the pending run of above-ASCII characters through the charset. */
    function flushLiteral(): UrlFailure | null {
        if (literal.length === 0) {
            return null;
        }

        const encoded = textToBytes(literal, charset);

        if (!encoded.ok) {
            // The codec counts within the run; the caller wants the position in
            // the whole input.
            return encoded.position === undefined
                ? encoded
                : { ...encoded, position: literalStart + encoded.position - 1 };
        }

        bytes.set(encoded.bytes, written);
        written += encoded.bytes.length;
        literal = "";

        return null;
    }

    while (index < input.length) {
        const code = input.charCodeAt(index);
        position += 1;

        if (code === PERCENT) {
            const pending = flushLiteral();

            if (pending) {
                return pending;
            }

            if (index + 2 >= input.length) {
                return { ok: false, reason: "truncated_escape", position };
            }

            const high = hexValue(input.charCodeAt(index + 1));
            const low = hexValue(input.charCodeAt(index + 2));

            if (high < 0 || low < 0) {
                return { ok: false, reason: "invalid_escape", position };
            }

            bytes[written] = (high << 4) | low;
            written += 1;
            index += 3;
            // The two hex digits were consumed alongside the `%`.
            position += 2;
            continue;
        }

        if (plusAsSpace && code === PLUS) {
            const pending = flushLiteral();

            if (pending) {
                return pending;
            }

            bytes[written] = SPACE;
            written += 1;
            index += 1;
            continue;
        }

        if (code <= ASCII_MAX) {
            const pending = flushLiteral();

            if (pending) {
                return pending;
            }

            bytes[written] = code;
            written += 1;
            index += 1;
            continue;
        }

        if (literal.length === 0) {
            literalStart = position;
        }

        // A surrogate pair is one character; taking it whole keeps the position
        // count honest and hands the codec a complete code point.
        const paired =
            isHighSurrogate(code) &&
            index + 1 < input.length &&
            isLowSurrogate(input.charCodeAt(index + 1));

        literal += paired ? input.slice(index, index + 2) : input[index];
        index += paired ? 2 : 1;
    }

    const pending = flushLiteral();

    if (pending) {
        return pending;
    }

    return { ok: true, bytes: bytes.slice(0, written) };
}

/* ----------------------------------------------------------------- sizes --- */

export function exceedsInputLimit(byteLength: number): boolean {
    return byteLength > MAX_URL_INPUT_BYTES;
}
