import { OUTPUT_FORMATS, type OutputFormat } from "../types";
import { formatEquation } from "./formats";

/**
 * The article's worked examples.
 *
 * Kept out of the message catalogue on purpose, and not only because a `{` opens
 * an ICU argument and a `<` opens a rich-text tag — every one of these would
 * have to be escaped twice over, in two locales, to say the same thing in both.
 * Notation is data. `\frac{a}{b}` reads the same in Bangla as in English, and a
 * translator has nothing to do with it.
 */

/** Every shape the converter reads, in the order the article's table lists them. */
export const NOTATION_KEYS = [
    "power",
    "fraction",
    "root",
    "sum",
    "lim",
    "greek",
    "relation",
    "function",
    "differential",
    "latex",
] as const;

export type NotationKey = (typeof NOTATION_KEYS)[number];

/** What a reader types. The prose beside each row lives in the catalogue. */
export const NOTATION_SAMPLES: Record<NotationKey, string> = {
    power: "x2 · x^2 · x²",
    fraction: "a/b",
    root: "sqrt(x) · cbrt(8) · abs(x)",
    sum: "sum i=1 to n of …",
    lim: "lim as x->0 of …",
    greek: "alpha · Omega · pi",
    relation: "<= · >= · != · -> · +- · *",
    function: "sin · cos · log · ln · exp",
    differential: "dx · dy · dt",
    latex: "\\frac{a}{b}",
};

const FORMAT_SAMPLE_SOURCE = "\\frac{a}{b}";

/**
 * MathML written short, by hand.
 *
 * The one sample not produced by the tool itself: KaTeX's real output opens with
 * a namespace declaration and carries a `<semantics>` wrapper and the original
 * TeX as an annotation, which is around two hundred characters and tells a
 * reader skimming a table nothing. The shape is the point here; the Copy button
 * gives the real thing.
 */
const MATHML_SAMPLE = "<math><mfrac><mi>a</mi><mi>b</mi></mfrac></math>";

export type FormatSample = {
    readonly format: OutputFormat;
    readonly sample: string;
};

/**
 * One sample per output format, three of the four generated by the formatter
 * itself — so a table row cannot quietly disagree with what Copy puts on the
 * clipboard.
 */
export const FORMAT_SAMPLES: readonly FormatSample[] = OUTPUT_FORMATS.map((format) => {
    if (format === "mathml") {
        return { format, sample: MATHML_SAMPLE };
    }

    const formatted = formatEquation(FORMAT_SAMPLE_SOURCE, format, true);

    return { format, sample: formatted.ok ? formatted.text : FORMAT_SAMPLE_SOURCE };
});
