import {
    TOOL_CATEGORIES,
    type Tool,
    type ToolCatalogStats,
    type ToolCategory,
    type ToolCategoryGroup,
    type ToolId,
} from "../types";

/**
 * Single source of truth for every tool ToolForge exposes or has queued.
 * Display names and descriptions live in the message catalogue under
 * `tools.<id>` so the registry itself stays locale-agnostic.
 */
const TOOLS: readonly Tool[] = [
    {
        id: "uuid",
        href: "/tools/uuid",
        category: "generators",
        status: "available",
        accent: "violet",
        icon: "fingerprint",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 100,
        keywords: [
            "guid",
            "uuid v4",
            "uuid v7",
            "uuid v1",
            "unique id",
            "random id",
            "rfc 9562",
            "identifier",
        ],
    },
    {
        id: "base64",
        href: "/tools/base64",
        category: "encoding",
        status: "available",
        accent: "cyan",
        icon: "binary",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 92,
        keywords: [
            "b64",
            "base64url",
            "data uri",
            "atob",
            "btoa",
            "mime",
            "encode",
            "decode",
            "binary to text",
        ],
    },
    {
        id: "jwt",
        href: "/tools/jwt",
        category: "security",
        status: "available",
        accent: "rose",
        icon: "key",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 88,
        keywords: [
            "json web token",
            "bearer token",
            "claims",
            "payload",
            "rfc 7519",
            "auth token",
            "decode jwt",
            "jws",
            "hs256",
            "rs256",
            "verify signature",
            "sign token",
        ],
    },
    {
        id: "hash",
        href: "/tools/hash",
        category: "security",
        status: "available",
        accent: "emerald",
        icon: "hash",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 84,
        keywords: [
            "sha-256",
            "sha-1",
            "sha-512",
            "md5",
            "checksum",
            "digest",
            "fingerprint",
            "message digest",
            "bcrypt",
            "argon2",
            "argon2id",
            "password hash",
            "salt",
            "cost factor",
            "verify hash",
            "compare hash",
        ],
    },
    {
        id: "json",
        href: "/tools/json",
        category: "formatting",
        status: "available",
        accent: "amber",
        icon: "braces",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 90,
        keywords: [
            "pretty print",
            "beautify",
            "minify",
            "validate",
            "formatter",
            "stringify",
            "indent",
            "prettify",
            "json validator",
            "json lint",
            "rfc 8259",
            "ecma-404",
            "trailing comma",
            "sort keys",
            "json repair",
        ],
    },
    {
        id: "url",
        href: "/tools/url",
        category: "encoding",
        status: "available",
        accent: "cyan",
        icon: "link",
        addedOn: "2026-07-28",
        featured: false,
        popularity: 70,
        keywords: [
            "percent encoding",
            "encodeuricomponent",
            "encodeuri",
            "decodeuricomponent",
            "query string",
            "escape",
            "unescape",
            "urlencode",
            "urldecode",
            "uri",
            "rfc 3986",
            "x-www-form-urlencoded",
            "double encoding",
        ],
    },
    {
        id: "markdown",
        href: "/tools/markdown",
        category: "formatting",
        status: "available",
        accent: "violet",
        icon: "markdown",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 86,
        keywords: [
            "md",
            "markdown preview",
            "markdown editor",
            "live preview",
            "readme",
            "gfm",
            "github flavored markdown",
            "commonmark",
            "mermaid",
            "katex",
            "latex",
            "math",
            "flowchart",
            "sequence diagram",
            "markdown to html",
            "md to pdf",
        ],
    },
    {
        id: "regex",
        href: "/tools/regex",
        category: "text",
        status: "available",
        accent: "violet",
        icon: "regex",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 78,
        keywords: [
            "regular expression",
            "pattern",
            "regexp",
            "match",
            "capture group",
            "test pattern",
            "regex tester",
            "regex101",
            "ecmascript regex",
            "pcre",
            "lookahead",
            "lookbehind",
            "backreference",
            "substitution",
            "search and replace",
            "catastrophic backtracking",
        ],
    },
    {
        id: "lorem",
        href: "/tools/lorem",
        category: "text",
        status: "available",
        accent: "amber",
        icon: "text",
        addedOn: "2026-07-28",
        featured: false,
        popularity: 82,
        keywords: [
            "lorem ipsum",
            "placeholder text",
            "dummy text",
            "filler text",
            "ipsum",
            "sample copy",
            "mock text",
            "random text",
            "text generator",
            "word generator",
            "paragraph generator",
            "random emoji",
            "emoji generator",
            "pangram",
            "bangla lorem",
            "cicero",
            "de finibus",
        ],
    },
    {
        id: "color",
        href: "/tools/color",
        category: "formatting",
        status: "available",
        accent: "rose",
        icon: "palette",
        addedOn: "2026-07-29",
        featured: true,
        popularity: 80,
        keywords: [
            "hex",
            "rgb",
            "hsl",
            "hsv",
            "hsb",
            "cmyk",
            "oklch",
            "colour",
            "color picker",
            "converter",
            "palette",
            "contrast",
            "wcag",
            "tailwind colors",
            "css named colors",
            "hex to rgb",
            "rgb to hex",
            "color scale",
            "shades and tints",
            "eyedropper",
        ],
    },
    {
        id: "cron",
        href: "/tools/cron",
        category: "formatting",
        status: "available",
        accent: "emerald",
        icon: "clock",
        addedOn: "2026-07-29",
        featured: false,
        popularity: 58,
        keywords: [
            "crontab",
            "schedule",
            "cron expression",
            "cron parser",
            "cron explainer",
            "crontab syntax",
            "quartz",
            "quartz cron",
            "next run",
            "next run times",
            "job timing",
            "cron generator",
            "kubernetes cronjob",
            "node-cron",
            "@daily",
            "@reboot",
        ],
    },
    {
        id: "timestamp",
        href: "/tools/timestamp",
        category: "formatting",
        status: "available",
        accent: "cyan",
        icon: "calendar",
        addedOn: "2026-07-29",
        featured: true,
        popularity: 74,
        keywords: [
            "unix time",
            "epoch",
            "epoch converter",
            "unix timestamp",
            "iso 8601",
            "rfc 2822",
            "rfc 3339",
            "date converter",
            "milliseconds",
            "microseconds",
            "nanoseconds",
            "utc",
            "time zone",
            "timezone converter",
            "iana",
            "daylight saving",
            "dst",
            "year 2038",
            "filetime",
            "excel serial date",
            "objectid",
            "uuid timestamp",
        ],
    },
    {
        id: "password",
        href: "/tools/password",
        category: "security",
        status: "available",
        accent: "violet",
        icon: "lock",
        addedOn: "2026-07-30",
        featured: false,
        popularity: 80,
        keywords: [
            "passphrase",
            "random password",
            "secure password",
            "entropy",
            "strong password",
            "password generator",
            "pin generator",
            "diceware",
            "time to crack",
            "crypto random",
        ],
    },
    {
        id: "qr",
        href: "/tools/qr",
        category: "generators",
        status: "available",
        accent: "amber",
        icon: "qrcode",
        addedOn: "2026-08-01",
        featured: true,
        popularity: 87,
        keywords: [
            "qr code",
            "qr generator",
            "qr reader",
            "qr scanner",
            "barcode",
            "scan",
            "vcard",
            "wifi qr",
            "mecard",
            "dynamic qr",
            "editable qr",
            "qr with logo",
            "iso 18004",
        ],
    },
    {
        id: "shortener",
        href: "/tools/shortener",
        category: "generators",
        status: "available",
        accent: "emerald",
        icon: "scissors",
        addedOn: "2026-08-02",
        featured: true,
        popularity: 85,
        keywords: [
            "url shortener",
            "link shortener",
            "short link",
            "short url",
            "tiny url",
            "tinyurl",
            "bitly",
            "custom alias",
            "vanity url",
            "branded link",
            "redirect",
            "editable link",
            "password protected link",
            "link expiry",
            "utm",
        ],
    },
    {
        id: "slug",
        href: "/tools/slug",
        category: "text",
        status: "available",
        accent: "emerald",
        icon: "slug",
        addedOn: "2026-08-02",
        featured: false,
        popularity: 48,
        keywords: [
            "url slug",
            "slugify",
            "permalink",
            "kebab case",
            "snake case",
            "seo url",
            "url friendly",
            "sanitize",
            "transliterate",
            "separator",
            "rfc 3986",
        ],
    },
    {
        id: "diff",
        href: "/tools/diff",
        category: "text",
        status: "planned",
        accent: "rose",
        icon: "diff",
        addedOn: "2026-09-03",
        featured: false,
        popularity: 56,
        keywords: ["compare", "text diff", "changes", "patch", "side by side", "unified diff"],
    },
    {
        id: "ai-image-detector",
        href: "/tools/ai-image-detector",
        category: "ai",
        status: "available",
        accent: "violet",
        icon: "photo",
        addedOn: "2026-07-29",
        featured: false,
        popularity: 68,
        keywords: [
            "ai image",
            "ai generated image",
            "fake image",
            "fake photo detector",
            "synthetic image",
            "deepfake",
            "midjourney detector",
            "dall-e detector",
            "stable diffusion detector",
            "flux detector",
            "real or ai",
        ],
    },
    {
        id: "ai-text-detector",
        href: "/tools/ai-text-detector",
        category: "ai",
        status: "available",
        accent: "cyan",
        icon: "scan",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 76,
        keywords: [
            "ai text",
            "ai written",
            "chatgpt detector",
            "gpt detector",
            "ai content check",
            "ai checker",
            "ai detector",
            "plagiarism",
            "llm detector",
            "perplexity",
            "burstiness",
        ],
    },
    {
        id: "watermark-remover",
        href: "/tools/watermark-remover",
        category: "ai",
        status: "available",
        accent: "amber",
        icon: "eraser",
        addedOn: "2026-07-30",
        featured: false,
        popularity: 72,
        keywords: [
            "remove watermark",
            "watermark remover",
            "image watermark",
            "ai watermark",
            "gemini watermark",
            "nano banana",
            "inpainting",
            "erase logo",
            "clean up photo",
            "object remover",
        ],
    },
];

export function getTools(): readonly Tool[] {
    return TOOLS;
}

export function getToolById(id: ToolId): Tool | undefined {
    return TOOLS.find((tool) => tool.id === id);
}

export function getAvailableTools(): readonly Tool[] {
    return TOOLS.filter((tool) => tool.status === "available");
}

/**
 * Search terms for the site-wide `keywords` meta tag. Planned tools are left
 * out: promising a QR generator that does not exist yet earns a bounce, not a
 * visitor.
 */
export function getToolKeywords(): readonly string[] {
    return [...new Set(getAvailableTools().flatMap((tool) => tool.keywords))];
}

/** Hand-picked tools for the overview grid, most popular first. */
export function getFeaturedTools(limit = 6): readonly Tool[] {
    return TOOLS.filter((tool) => tool.featured)
        .toSorted((a, b) => b.popularity - a.popularity)
        .slice(0, limit);
}

export function getPopularTools(limit = 4): readonly Tool[] {
    return TOOLS.toSorted((a, b) => b.popularity - a.popularity).slice(0, limit);
}

/** Newest first, so the overview can surface what just landed. */
export function getRecentTools(limit = 4): readonly Tool[] {
    return TOOLS.toSorted((a, b) => b.addedOn.localeCompare(a.addedOn)).slice(0, limit);
}

export function getToolsByCategory(): readonly ToolCategoryGroup[] {
    return TOOL_CATEGORIES.map((category) => {
        const tools = TOOLS.filter((tool) => tool.category === category);

        return {
            category,
            tools,
            availableCount: tools.filter((tool) => tool.status === "available").length,
        } satisfies ToolCategoryGroup;
    });
}

export function getToolsInCategory(category: ToolCategory): readonly Tool[] {
    return TOOLS.filter((tool) => tool.category === category);
}

export function getToolCatalogStats(): ToolCatalogStats {
    const available = getAvailableTools().length;

    return {
        available,
        planned: TOOLS.length - available,
        total: TOOLS.length,
        categories: TOOL_CATEGORIES.length,
    };
}
