import {
    TOOL_CATEGORIES,
    type Tool,
    type ToolCatalogStats,
    type ToolCategory,
    type ToolCategoryGroup,
    type ToolId,
} from "../types";

/**
 * Single source of truth for every tool ToolForge exposes or has queued.
 * Display names and descriptions live in the message catalogue under
 * `tools.<id>` so the registry itself stays locale-agnostic.
 */
const TOOLS: readonly Tool[] = [
    {
        id: "uuid",
        href: "/tools/uuid",
        category: "generators",
        status: "available",
        runsOn: "browser",
        accent: "violet",
        icon: "fingerprint",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 100,
        keywords: [
            "guid",
            "uuid v4",
            "uuid v7",
            "uuid v1",
            "unique id",
            "random id",
            "rfc 9562",
            "identifier",
        ],
    },
    {
        id: "base64",
        href: "/tools/base64",
        category: "encoding",
        status: "available",
        runsOn: "browser",
        accent: "cyan",
        icon: "binary",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 92,
        keywords: [
            "b64",
            "base64url",
            "data uri",
            "atob",
            "btoa",
            "mime",
            "encode",
            "decode",
            "binary to text",
        ],
    },
    {
        id: "jwt",
        href: "/tools/jwt",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "rose",
        icon: "key",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 88,
        keywords: [
            "json web token",
            "bearer token",
            "claims",
            "payload",
            "rfc 7519",
            "auth token",
            "decode jwt",
            "jws",
            "hs256",
            "rs256",
            "verify signature",
            "sign token",
        ],
    },
    {
        id: "hash",
        href: "/tools/hash",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "emerald",
        icon: "hash",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 84,
        keywords: [
            "sha-256",
            "sha-1",
            "sha-512",
            "md5",
            "checksum",
            "digest",
            "fingerprint",
            "message digest",
            "bcrypt",
            "argon2",
            "argon2id",
            "password hash",
            "salt",
            "cost factor",
            "verify hash",
            "compare hash",
        ],
    },
    {
        id: "aes",
        href: "/tools/aes",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "cyan",
        icon: "shield",
        addedOn: "2026-08-08",
        featured: false,
        popularity: 87,
        keywords: [
            "aes",
            "aes encryption",
            "aes decrypt",
            "encrypt text",
            "decrypt text",
            "aes-256",
            "aes-128",
            "aes-gcm",
            "aes-cbc",
            "aes-ctr",
            "rijndael",
            "symmetric encryption",
            "cipher",
            "pbkdf2",
            "key derivation",
            "initialization vector",
            "salt",
            "fips 197",
            "nist sp 800-38a",
            "webcrypto",
            "subtlecrypto",
            "cryptojs",
        ],
    },
    {
        id: "rsa",
        href: "/tools/rsa",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "amber",
        icon: "certificate",
        addedOn: "2026-08-08",
        featured: false,
        popularity: 81,
        keywords: [
            "rsa",
            "rsa key generator",
            "generate rsa key",
            "key pair",
            "keypair",
            "public key",
            "private key",
            "asymmetric encryption",
            "pem",
            "der",
            "jwk",
            "pkcs#1",
            "pkcs1",
            "pkcs#8",
            "pkcs8",
            "spki",
            "rs256",
            "ps256",
            "rsa-oaep",
            "rsassa-pkcs1-v1_5",
            "rsa-pss",
            "openssl genrsa",
            "ssh-keygen",
            "public exponent",
            "65537",
            "modulus",
            "rfc 8017",
            "digital signature",
            "webcrypto",
        ],
    },
    {
        id: "rsa-encrypt",
        href: "/tools/rsa-encrypt",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "amber",
        icon: "lock-code",
        addedOn: "2026-08-09",
        featured: false,
        popularity: 77,
        keywords: [
            "rsa encrypt",
            "rsa decrypt",
            "rsa encryption online",
            "encrypt with public key",
            "decrypt with private key",
            "rsa-oaep",
            "oaep",
            "asymmetric encryption",
            "public key encryption",
            "pem",
            "der",
            "jwk",
            "pkcs#1",
            "pkcs#8",
            "spki",
            "openssl rsautl",
            "openssl pkeyutl",
            "rfc 8017",
            "key wrapping",
            "session key",
            "webcrypto",
        ],
    },
    {
        id: "json",
        href: "/tools/json",
        category: "formatting",
        status: "available",
        runsOn: "browser",
        accent: "amber",
        icon: "braces",
        addedOn: "2026-07-27",
        featured: true,
        popularity: 90,
        keywords: [
            "pretty print",
            "beautify",
            "minify",
            "validate",
            "formatter",
            "stringify",
            "indent",
            "prettify",
            "json validator",
            "json lint",
            "rfc 8259",
            "ecma-404",
            "trailing comma",
            "sort keys",
            "json repair",
        ],
    },
    {
        id: "url",
        href: "/tools/url",
        category: "encoding",
        status: "available",
        runsOn: "browser",
        accent: "cyan",
        icon: "link",
        addedOn: "2026-07-28",
        featured: false,
        popularity: 70,
        keywords: [
            "percent encoding",
            "encodeuricomponent",
            "encodeuri",
            "decodeuricomponent",
            "query string",
            "escape",
            "unescape",
            "urlencode",
            "urldecode",
            "uri",
            "rfc 3986",
            "x-www-form-urlencoded",
            "double encoding",
        ],
    },
    {
        id: "url-parser",
        href: "/tools/url-parser",
        category: "encoding",
        status: "available",
        runsOn: "browser",
        accent: "violet",
        icon: "world",
        addedOn: "2026-08-02",
        featured: false,
        popularity: 75,
        keywords: [
            "url parser",
            "parse url",
            "url components",
            "query string parser",
            "query parameters",
            "searchparams",
            "urlsearchparams",
            "whatwg url",
            "url breakdown",
            "url inspector",
            "protocol",
            "hostname",
            "port",
            "path",
            "fragment",
            "utm parameters",
            "rfc 3986",
        ],
    },
    {
        id: "curl",
        href: "/tools/curl",
        category: "encoding",
        status: "available",
        runsOn: "browser",
        accent: "rose",
        icon: "terminal",
        addedOn: "2026-08-03",
        featured: false,
        popularity: 83,
        keywords: [
            "curl to fetch",
            "fetch to curl",
            "curl converter",
            "convert curl",
            "curl to javascript",
            "curl to js",
            "curl to axios",
            "curl to node",
            "copy as curl",
            "curl command",
            "curl parser",
            "curl builder",
            "http request",
            "api request",
            "rest client",
            "javascript fetch",
            "undici",
            "node https",
            "powershell curl",
            "curl windows",
        ],
    },
    {
        id: "markdown",
        href: "/tools/markdown",
        category: "formatting",
        status: "available",
        runsOn: "browser",
        accent: "violet",
        icon: "markdown",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 86,
        keywords: [
            "md",
            "markdown preview",
            "markdown editor",
            "live preview",
            "readme",
            "gfm",
            "github flavored markdown",
            "commonmark",
            "mermaid",
            "katex",
            "latex",
            "math",
            "flowchart",
            "sequence diagram",
            "markdown to html",
            "md to pdf",
        ],
    },
    {
        id: "regex",
        href: "/tools/regex",
        category: "text",
        status: "available",
        runsOn: "browser",
        accent: "violet",
        icon: "regex",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 78,
        keywords: [
            "regular expression",
            "pattern",
            "regexp",
            "match",
            "capture group",
            "test pattern",
            "regex tester",
            "regex101",
            "ecmascript regex",
            "pcre",
            "lookahead",
            "lookbehind",
            "backreference",
            "substitution",
            "search and replace",
            "catastrophic backtracking",
        ],
    },
    {
        id: "lorem",
        href: "/tools/lorem",
        category: "text",
        status: "available",
        runsOn: "browser",
        accent: "amber",
        icon: "text",
        addedOn: "2026-07-28",
        featured: false,
        popularity: 82,
        keywords: [
            "lorem ipsum",
            "placeholder text",
            "dummy text",
            "filler text",
            "ipsum",
            "sample copy",
            "mock text",
            "random text",
            "text generator",
            "word generator",
            "paragraph generator",
            "random emoji",
            "emoji generator",
            "pangram",
            "bangla lorem",
            "cicero",
            "de finibus",
        ],
    },
    {
        id: "color",
        href: "/tools/color",
        category: "formatting",
        status: "available",
        runsOn: "browser",
        accent: "rose",
        icon: "palette",
        addedOn: "2026-07-29",
        featured: true,
        popularity: 80,
        keywords: [
            "hex",
            "rgb",
            "hsl",
            "hsv",
            "hsb",
            "cmyk",
            "oklch",
            "colour",
            "color picker",
            "converter",
            "palette",
            "contrast",
            "wcag",
            "tailwind colors",
            "css named colors",
            "hex to rgb",
            "rgb to hex",
            "color scale",
            "shades and tints",
            "eyedropper",
        ],
    },
    {
        id: "cron",
        href: "/tools/cron",
        category: "formatting",
        status: "available",
        runsOn: "browser",
        accent: "emerald",
        icon: "clock",
        addedOn: "2026-07-29",
        featured: false,
        popularity: 58,
        keywords: [
            "crontab",
            "schedule",
            "cron expression",
            "cron parser",
            "cron explainer",
            "crontab syntax",
            "quartz",
            "quartz cron",
            "next run",
            "next run times",
            "job timing",
            "cron generator",
            "kubernetes cronjob",
            "node-cron",
            "@daily",
            "@reboot",
        ],
    },
    {
        id: "timestamp",
        href: "/tools/timestamp",
        category: "formatting",
        status: "available",
        runsOn: "browser",
        accent: "cyan",
        icon: "calendar",
        addedOn: "2026-07-29",
        featured: true,
        popularity: 74,
        keywords: [
            "unix time",
            "epoch",
            "epoch converter",
            "unix timestamp",
            "iso 8601",
            "rfc 2822",
            "rfc 3339",
            "date converter",
            "milliseconds",
            "microseconds",
            "nanoseconds",
            "utc",
            "time zone",
            "timezone converter",
            "iana",
            "daylight saving",
            "dst",
            "year 2038",
            "filetime",
            "excel serial date",
            "objectid",
            "uuid timestamp",
        ],
    },
    {
        id: "password",
        href: "/tools/password",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "violet",
        icon: "lock",
        addedOn: "2026-07-30",
        featured: false,
        popularity: 80,
        keywords: [
            "passphrase",
            "random password",
            "secure password",
            "entropy",
            "strong password",
            "password generator",
            "pin generator",
            "diceware",
            "time to crack",
            "crypto random",
        ],
    },
    {
        id: "secret",
        href: "/tools/secret",
        category: "security",
        status: "available",
        runsOn: "browser",
        accent: "emerald",
        icon: "dice",
        addedOn: "2026-08-13",
        featured: false,
        popularity: 76,
        keywords: [
            "secret key",
            "api key",
            "openssl rand",
            "random bytes",
            "nextauth secret",
            "auth secret",
            "jwt secret",
            "signing key",
            "encryption key",
            "session secret",
            "webhook secret",
            "totp secret",
            "base64url",
            "csprng",
            "env variable",
        ],
    },
    {
        id: "qr",
        href: "/tools/qr",
        category: "generators",
        status: "available",
        runsOn: "hybrid",
        accent: "amber",
        icon: "qrcode",
        addedOn: "2026-08-01",
        featured: true,
        popularity: 87,
        keywords: [
            "qr code",
            "qr generator",
            "qr reader",
            "qr scanner",
            "barcode",
            "scan",
            "vcard",
            "wifi qr",
            "mecard",
            "dynamic qr",
            "editable qr",
            "qr with logo",
            "iso 18004",
        ],
    },
    {
        id: "shortener",
        href: "/tools/shortener",
        category: "generators",
        status: "available",
        runsOn: "server",
        accent: "emerald",
        icon: "scissors",
        addedOn: "2026-08-02",
        featured: true,
        popularity: 85,
        keywords: [
            "url shortener",
            "link shortener",
            "short link",
            "short url",
            "tiny url",
            "tinyurl",
            "bitly",
            "custom alias",
            "vanity url",
            "branded link",
            "redirect",
            "editable link",
            "password protected link",
            "link expiry",
            "utm",
        ],
    },
    {
        id: "slug",
        href: "/tools/slug",
        category: "text",
        status: "available",
        runsOn: "browser",
        accent: "emerald",
        icon: "slug",
        addedOn: "2026-08-02",
        featured: false,
        popularity: 48,
        keywords: [
            "url slug",
            "slugify",
            "permalink",
            "kebab case",
            "snake case",
            "seo url",
            "url friendly",
            "sanitize",
            "transliterate",
            "separator",
            "rfc 3986",
        ],
    },
    {
        id: "text-case",
        href: "/tools/text-case",
        category: "text",
        status: "available",
        runsOn: "browser",
        accent: "cyan",
        icon: "case",
        addedOn: "2026-08-14",
        featured: false,
        popularity: 80,
        keywords: [
            "convert case",
            "text case",
            "uppercase",
            "lowercase",
            "sentence case",
            "title case",
            "capitalize",
            "caps lock",
            "alternating case",
            "camelcase",
            "pascalcase",
            "snake case",
            "kebab case",
            "constant case",
        ],
    },
    {
        id: "diff",
        href: "/tools/diff",
        category: "text",
        status: "available",
        runsOn: "browser",
        accent: "rose",
        icon: "diff",
        addedOn: "2026-08-02",
        featured: false,
        popularity: 86,
        keywords: [
            "compare",
            "text diff",
            "diff checker",
            "changes",
            "patch",
            "side by side",
            "unified diff",
            "compare text",
            "file compare",
            "merge",
        ],
    },
    {
        id: "image-compressor",
        href: "/tools/image-compressor",
        category: "media",
        status: "available",
        // Everything it does happens in the tab. Pulling a picture in by its
        // public address does not, because a cross-origin image taints the
        // canvas — the URL field says so above the controls.
        runsOn: "hybrid",
        accent: "emerald",
        icon: "compress",
        addedOn: "2026-08-03",
        featured: true,
        popularity: 84,
        keywords: [
            "compress image",
            "image compressor",
            "image optimizer",
            "optimize images",
            "reduce image size",
            "reduce file size",
            "shrink image",
            "photo compressor",
            "jpeg compressor",
            "png compressor",
            "webp converter",
            "convert to webp",
            "resize image",
            "image resizer",
            "bulk image compression",
            "batch compress",
            "lossy compression",
            "tinypng",
        ],
    },
    {
        id: "image-converter",
        href: "/tools/image-converter",
        category: "media",
        status: "available",
        // Everything it does happens in the tab. Pulling a picture in by its
        // public address does not, because a cross-origin image taints the
        // canvas — the URL field says so above the controls.
        runsOn: "hybrid",
        accent: "cyan",
        icon: "transform",
        addedOn: "2026-08-03",
        featured: true,
        popularity: 88,
        keywords: [
            "image converter",
            "convert image",
            "png to jpg",
            "jpg to png",
            "png to webp",
            "webp to png",
            "jpg to webp",
            "convert to avif",
            "heic alternative",
            "favicon generator",
            "favicon.ico",
            "make favicon",
            "ico converter",
            "png to ico",
            "apple touch icon",
            "web app manifest",
            "site.webmanifest",
            "app icon generator",
            "transparent background",
            "flatten transparency",
            "batch convert images",
        ],
    },
    {
        id: "image-resizer",
        href: "/tools/image-resizer",
        category: "media",
        status: "available",
        // Cropping and resizing never leave the tab. Pulling a picture in by
        // its public address does, because a cross-origin image taints the
        // canvas — the URL field says so above the controls.
        runsOn: "hybrid",
        accent: "violet",
        icon: "crop",
        addedOn: "2026-08-12",
        featured: true,
        popularity: 86,
        keywords: [
            "image resizer",
            "resize image",
            "crop image",
            "image cropper",
            "crop photo",
            "passport photo",
            "passport size photo",
            "45x55",
            "bangladesh passport photo",
            "nid photo size",
            "stamp size photo",
            "visa photo",
            "photo size converter",
            "aspect ratio crop",
            "custom aspect ratio",
            "resize by percentage",
            "resize in inches",
            "resize in mm",
            "dpi",
            "300 dpi",
            "print size",
            "social media image size",
            "instagram size",
            "facebook cover size",
            "youtube thumbnail size",
            "lossless crop",
            "change image dimensions",
        ],
    },
    {
        id: "blur-placeholder",
        href: "/tools/blur-placeholder",
        category: "media",
        status: "available",
        // Everything it does happens in the tab. Pulling a picture in by its
        // public address does not, because a cross-origin image taints the
        // canvas — the URL field says so above the controls.
        runsOn: "hybrid",
        accent: "violet",
        icon: "blur",
        addedOn: "2026-08-03",
        featured: false,
        popularity: 70,
        keywords: [
            "blurhash",
            "blurhash generator",
            "blurhash decoder",
            "blur placeholder",
            "image placeholder",
            "blurdataurl",
            "next image placeholder",
            "placeholder blur",
            "lqip",
            "low quality image placeholder",
            "progressive image loading",
            "lazy loading placeholder",
            "layout shift",
            "react-blurhash",
            "base83",
            "image hash",
        ],
    },
    {
        id: "ai-image-detector",
        href: "/tools/ai-image-detector",
        category: "ai",
        status: "available",
        runsOn: "server",
        accent: "violet",
        icon: "photo",
        addedOn: "2026-07-29",
        featured: false,
        popularity: 68,
        keywords: [
            "ai image",
            "ai generated image",
            "fake image",
            "fake photo detector",
            "synthetic image",
            "deepfake",
            "midjourney detector",
            "dall-e detector",
            "stable diffusion detector",
            "flux detector",
            "real or ai",
        ],
    },
    {
        id: "ai-text-detector",
        href: "/tools/ai-text-detector",
        category: "ai",
        status: "available",
        runsOn: "server",
        accent: "cyan",
        icon: "scan",
        addedOn: "2026-07-28",
        featured: true,
        popularity: 76,
        keywords: [
            "ai text",
            "ai written",
            "chatgpt detector",
            "gpt detector",
            "ai content check",
            "ai checker",
            "ai detector",
            "plagiarism",
            "llm detector",
            "perplexity",
            "burstiness",
        ],
    },
    {
        id: "watermark-remover",
        href: "/tools/watermark-remover",
        category: "ai",
        status: "available",
        runsOn: "server",
        accent: "amber",
        icon: "eraser",
        addedOn: "2026-07-30",
        featured: false,
        popularity: 72,
        keywords: [
            "remove watermark",
            "watermark remover",
            "image watermark",
            "ai watermark",
            "gemini watermark",
            "nano banana",
            "inpainting",
            "erase logo",
            "clean up photo",
            "object remover",
        ],
    },
    {
        id: "domain-inspector",
        href: "/tools/domain-inspector",
        category: "network",
        status: "available",
        runsOn: "server",
        accent: "emerald",
        icon: "radar",
        addedOn: "2026-08-04",
        featured: true,
        popularity: 86,
        keywords: [
            "dns lookup",
            "dig",
            "nslookup",
            "whois",
            "rdap",
            "domain lookup",
            "mx record",
            "txt record",
            "spf",
            "dmarc",
            "caa",
            "dnssec",
            "reverse dns",
            "asn",
            "ip lookup",
            "ssl checker",
            "certificate expiry",
            "http headers",
            "security headers",
            "tech stack",
            "what cms",
            "hosting provider",
            "nameservers",
            "domain expiry",
        ],
    },
    {
        id: "bson",
        href: "/tools/bson",
        category: "encoding",
        status: "available",
        runsOn: "browser",
        accent: "amber",
        icon: "database",
        addedOn: "2026-08-04",
        featured: false,
        popularity: 71,
        keywords: [
            "bson",
            "bson to json",
            "json to bson",
            "bsondump",
            "mongodb",
            "mongo",
            "extended json",
            "ejson",
            "canonical extended json",
            "relaxed extended json",
            "mongoexport",
            "mongoimport",
            "objectid",
            "decimal128",
            "toon",
            "toon format",
            "token oriented object notation",
            "json to toon",
            "toon to json",
            "llm prompt tokens",
            "token efficient json",
            "binary json",
        ],
    },
    {
        id: "port-scanner",
        href: "/tools/port-scanner",
        category: "network",
        status: "available",
        runsOn: "server",
        accent: "rose",
        icon: "network",
        addedOn: "2026-08-04",
        featured: false,
        popularity: 79,
        keywords: [
            "port scanner",
            "port checker",
            "open port check",
            "check open ports",
            "tcp port scan",
            "is port open",
            "port test",
            "nmap online",
            "online port scanner",
            "firewall test",
            "check my ports",
            "rdp exposed",
            "ssh port open",
            "port 3389",
            "port 22",
            "port 445",
            "common ports",
            "filtered port",
        ],
    },
    {
        id: "mock-server",
        // A section, not a page: the studio is a route tree under /mock with
        // its own navigation, so it opts out of the /tools/<id> rule and out of
        // every grid where a multi-page app between two single-page utilities
        // would read as a mistake.
        href: "/mock",
        isSection: true,
        category: "network",
        status: "available",
        runsOn: "server",
        accent: "cyan",
        icon: "server",
        addedOn: "2026-08-05",
        featured: false,
        popularity: 60,
        keywords: [
            "mock api",
            "mock server",
            "api mocking",
            "fake api",
            "stub api",
            "rest mock",
            "json server",
            "http mock",
            "prototype api",
        ],
    },
    {
        id: "json-server",
        // A section, not a page: the studio is a route tree under /json with its
        // own navigation, so it opts out of the /tools/<id> rule and out of
        // every grid where a multi-page app between two single-page utilities
        // would read as a mistake.
        href: "/json",
        isSection: true,
        category: "network",
        status: "available",
        runsOn: "server",
        accent: "amber",
        icon: "database",
        addedOn: "2026-08-06",
        featured: false,
        popularity: 58,
        keywords: [
            "json server",
            "json-server",
            "db.json",
            "fake rest api",
            "rest api mock",
            "hosted json server",
            "prototype api",
            "crud api",
            "typicode",
        ],
    },
    {
        id: "graphql-server",
        // A section for the same reason the JSON Server Studio is one: a route
        // tree with its own navigation, not a page.
        href: "/graphql",
        isSection: true,
        category: "network",
        status: "available",
        runsOn: "server",
        accent: "rose",
        icon: "graph",
        addedOn: "2026-08-06",
        featured: false,
        popularity: 56,
        keywords: [
            "graphql server",
            "graphql api",
            "fake graphql api",
            "mock graphql",
            "graphql from json",
            "hosted graphql",
            "graphql playground",
            "schema from json",
            "graphql sandbox",
            "sdl",
        ],
    },
];

export function getTools(): readonly Tool[] {
    return TOOLS;
}

export function getToolById(id: ToolId): Tool | undefined {
    return TOOLS.find((tool) => tool.id === id);
}

export function getAvailableTools(): readonly Tool[] {
    return TOOLS.filter((tool) => tool.status === "available");
}

/**
 * Everything that is a single page, which is what every ranked grid means by
 * "tool". A section has its own navigation and belongs in the rail above them,
 * not between two utilities in a popularity list.
 */
function getPageTools(): readonly Tool[] {
    return TOOLS.filter((tool) => tool.isSection !== true);
}

/**
 * Search terms for the site-wide `keywords` meta tag. Planned tools are left
 * out: promising a QR generator that does not exist yet earns a bounce, not a
 * visitor.
 */
export function getToolKeywords(): readonly string[] {
    return [...new Set(getAvailableTools().flatMap((tool) => tool.keywords))];
}

/** Hand-picked tools for the overview grid, most popular first. */
export function getFeaturedTools(limit = 6): readonly Tool[] {
    return getPageTools()
        .filter((tool) => tool.featured)
        .toSorted((a, b) => b.popularity - a.popularity)
        .slice(0, limit);
}

export function getPopularTools(limit = 4): readonly Tool[] {
    return getPageTools()
        .toSorted((a, b) => b.popularity - a.popularity)
        .slice(0, limit);
}

/**
 * Suggestions for the foot of a tool page.
 *
 * Shipped tools only — a "planned" card at the end of a page is a dead end, not
 * a next step. Neighbours from the same category lead, because someone who just
 * decoded a JWT is likelier to want a hash than a lorem generator; the rest of
 * the toolbox follows by popularity.
 */
export function getRelatedTools(id: ToolId, limit = 3): readonly Tool[] {
    const category = getToolById(id)?.category;

    return getAvailableTools()
        .filter((tool) => tool.id !== id && tool.isSection !== true)
        .toSorted((a, b) => {
            const byCategory = Number(b.category === category) - Number(a.category === category);

            return byCategory !== 0 ? byCategory : b.popularity - a.popularity;
        })
        .slice(0, limit);
}

/** Newest first, so the overview can surface what just landed. */
export function getRecentTools(limit = 4): readonly Tool[] {
    return getPageTools()
        .toSorted((a, b) => b.addedOn.localeCompare(a.addedOn))
        .slice(0, limit);
}

export function getToolsByCategory(): readonly ToolCategoryGroup[] {
    return TOOL_CATEGORIES.map((category) => {
        const tools = getPageTools().filter((tool) => tool.category === category);

        return {
            category,
            tools,
            availableCount: tools.filter((tool) => tool.status === "available").length,
        } satisfies ToolCategoryGroup;
    });
}

export function getToolsInCategory(category: ToolCategory): readonly Tool[] {
    return getPageTools().filter((tool) => tool.category === category);
}

export function getToolCatalogStats(): ToolCatalogStats {
    const shipped = getAvailableTools();

    return {
        available: shipped.length,
        planned: TOOLS.length - shipped.length,
        total: TOOLS.length,
        categories: TOOL_CATEGORIES.length,
        // Only `"browser"`. A hybrid is local until its one networked feature is
        // used, and a count that folds it in here would be a promise the tool
        // cannot keep for the reader who uses that feature.
        browserOnly: shipped.filter((tool) => tool.runsOn === "browser").length,
    };
}
