import type { ImageFileLimits } from "@/modules/tools/domain/image-file";

/**
 * Ceiling enforced upstream, mirrored here so the browser can refuse a hopeless
 * upload before spending a model call on it — the worker's budget is finite and
 * shared by everyone.
 */
export const MAX_IMAGE_BYTES = 10 * 1024 * 1024;

/**
 * What the worker's image pipeline will decode. Narrower than the detector's
 * list on purpose: an animated GIF cannot survive being repainted as a single
 * still, so accepting one would promise something the model cannot deliver.
 */
export const ALLOWED_IMAGE_TYPES = ["image/jpeg", "image/png", "image/webp"] as const;

export type AllowedImageType = (typeof ALLOWED_IMAGE_TYPES)[number];

/** `accept` for the file input — a hint to the picker, never a substitute for the check. */
export const IMAGE_ACCEPT_ATTRIBUTE = ALLOWED_IMAGE_TYPES.join(",");

/**
 * The pair the shared file check reads, exported as one value so the island and
 * the server action can never drift into gating uploads differently.
 */
export const IMAGE_FILE_LIMITS: ImageFileLimits<AllowedImageType> = {
    allowedTypes: ALLOWED_IMAGE_TYPES,
    maxBytes: MAX_IMAGE_BYTES,
};

/**
 * The mask is generated by this tool, not chosen by the reader, so the check on
 * it is a guard against a hand-built request rather than a service to a user.
 */
export const MASK_FILE_LIMITS: ImageFileLimits<"image/png"> = {
    allowedTypes: ["image/png"],
    maxBytes: MAX_IMAGE_BYTES,
};

/**
 * Side of the square canvas the inpainting model works in. Both the crop and its
 * mask are resized to exactly this before they are sent, which makes the
 * worker's own `scale-down` a no-op: it is told 512x512, so it must be handed
 * 512x512 or the geometry it reports and the geometry it received disagree.
 */
export const MODEL_CANVAS_SIZE = 512;

/**
 * How much room around the painted area the model is given for context, as a
 * share of the mask's longer side. Too little and it has nothing to match the
 * repaint against; too much and the watermark shrinks into a handful of pixels.
 */
export const REGION_PADDING_RATIO = 0.4;

/**
 * Floor on the square that gets cropped. A 40 px logo cropped at 40 px would be
 * blown up 13x into the model canvas, and it would answer with invented detail
 * at a scale nothing else in the picture shares.
 */
export const MIN_REGION_SIDE = 256;

/**
 * How far the repainted patch fades into the original at its edge, as a share of
 * the region's side. A hard edge is visible even when the repaint is good: the
 * model's pixels went through a different encoder than the ones beside them.
 */
export const REGION_FEATHER_RATIO = 0.012;

/** Below a couple of pixels a feather stops being a blend and becomes a seam. */
export const MIN_FEATHER_PX = 2;

/**
 * How far the mask sent upstream is grown past what the reader painted, in model
 * canvas pixels. A watermark's anti-aliased fringe sits just outside the shape a
 * hand traces around it, and a fringe left behind reads as a failed removal.
 */
export const MASK_DILATION_PX = 4;

/** Brush diameter, in the preview's own display pixels. */
export const MIN_BRUSH_SIZE = 6;
export const MAX_BRUSH_SIZE = 96;
export const DEFAULT_BRUSH_SIZE = 28;
export const BRUSH_SIZE_STEP = 2;

/**
 * How far one arrow key moves the keyboard crosshair, as a share of the
 * picture's width. A brush is a pointer gesture by nature, so the crosshair is
 * the only way the mask can be painted without one.
 */
export const CARET_STEP_RATIO = 0.02;

/** Held `Shift` covers this many steps at once, for crossing a large picture. */
export const CARET_STEP_MULTIPLIER = 5;

/**
 * Ceiling on the overlay canvas's longer side. The strokes are recorded in image
 * pixels whatever this is, so a 4000 px photo gets a canvas a browser will
 * happily keep in memory instead of a 48 MB one.
 */
export const OVERLAY_MAX_SIDE = 1280;

/**
 * The colour the mask is painted in on screen.
 *
 * A literal rather than a design token, and the one place in this feature that is
 * allowed to be: it sits over the reader's own photograph, not over a themed
 * surface, so it has to hold up against arbitrary pixels rather than match either
 * palette. Translucent, so what is underneath stays visible while it is covered.
 */
export const MASK_PAINT_COLOR = "rgba(255, 62, 116, 0.5)";

/** The keyboard crosshair, drawn only while the canvas has focus. */
export const CARET_RING_COLOR = "rgba(255, 255, 255, 0.95)";
export const CARET_SHADOW_COLOR = "rgba(0, 0, 0, 0.65)";

/**
 * Twenty diffusion steps plus two image transforms, on a queue shared with every
 * other caller. Past this the reader deserves to hear that it stalled rather
 * than watch a spinner.
 */
export const REMOVAL_TIMEOUT_MS = 90_000;

/**
 * A 512x512 PNG is a few hundred kilobytes. An order of magnitude past that is
 * not a picture, and it crosses the action boundary base64-encoded, so it is
 * refused before it is turned into a 1.3x larger string.
 */
export const MAX_RESULT_BYTES = 4 * 1024 * 1024;

/**
 * How much of an upstream failure's body is kept for the log. Enough to carry a
 * model's validation message, short of a whole stack trace.
 */
export const MAX_UPSTREAM_ERROR_LENGTH = 300;

/** Field names the worker reads its two uploads from. */
export const IMAGE_FORM_FIELD = "image";
export const MASK_FORM_FIELD = "mask";

export const TOKEN_FORM_FIELD = "token";

/** Sent to Turnstile so its dashboard separates this widget from any other. */
export const TURNSTILE_ACTION = "watermark-remover";
